class: inverse, middle, center

# Basic concepts illustrated using a two-level factor (pp.3--8)

---

class: inverse, middle
<!-- class: inverse, middle, split-50 -->

## 1要因2水準の実験で，応答変数の平均値を比較

- シミュレーション用データを作る
  - [`mixedDesign()`](http://read.psych.uni-potsdam.de/attachments/article/188/mixedDesign.v0.6.3.R)を使う
  - 1要因2水準
      1. F1: 0.8秒
      1. F2: 0.4秒
  - 実験参加者数10人

---

<!--
https://stackoverflow.com/questions/67750561/vertically-scrollable-code-with-rstudio-and-xaringan
-->

`r chunk_reveal("simdat")`

<!--
#### the number of between-subject factors
-->

```{r simdat, include = FALSE}
mixedDesign(
  B = 2,
  W = NULL,
  n = 5,
  M = matrix(
    c(0.8, 0.4),
    nrow = 2,
    ncol = 1,
    byrow = FALSE
  ),
  SD = 0.20,
  long = TRUE
) |>
  rename(F = B_A) |>
  mutate(
    F = case_when(
      F == "A1" ~ "F1",
      F == "A2" ~ "F2",
      TRUE ~ "NA_character_"
    )
  ) -> 
  simdat

str(simdat)
```

```{r fig-simdat, include = FALSE}
simdat  |>
  group_by(F) |>
  summarize(
    N = length(DV),
    M = mean(DV),
    SD = sd(DV),
    SE = SD / sqrt(N)
  ) |>
  ungroup() |>
  (
    \(d){
      qplot(
        x = F, y = M,
        group = 1,
        data = d,
        geom = c("point", "line")
      )
    }
  )() +
  geom_errorbar(
    aes(
      max = M + SE,
      min = M - SE
    ),
    width = 0
  ) +
  labs(
    y = "Mean DV",
    x = "Factor F"
  )
```